export const newsTopics = [
    "Artificial Intelligence Writes Hit Pop Song",
    "Global Coffee Shortage Looms as Brazil Faces Drought",
    "New Sustainable Fashion Line Made from Ocean Plastic",
    "Mars Colony Simulation Enters Second Year",
    "Breakthrough in Alzheimer's Treatment Shows Promise",
    "World's First Successful Brain Transplant Performed",
    "Cryptocurrency Becomes Legal Tender in Major European Nation",
    "Ancient Mayan City Discovered Using Satellite Imagery",
    "Self-Driving Cars Reduce Traffic Fatalities by 50%",
    "New Plant Species Found in Amazon Can Absorb Pollution",
    "Global Chess Tournament Ends in Surprise Upset",
    "Quantum Computer Solves Century-Old Math Problem",
    "Revolutionary Diet Pill Claims to Mimic Effects of Exercise",
    "First Commercial Space Hotel Set to Open Next Year",
    "Artificial Leaf Converts CO2 to Clean Fuel Efficiently",
    "World's Oldest Person Celebrates 120th Birthday",
    "New Tech Allows Paralyzed Individuals to Communicate via Thought",
    "Major Breakthrough in Nuclear Fusion Energy Generation",
    "Global Initiative to Plant One Trillion Trees Launched",
    "AI-Generated Art Sells for Record Price at Auction",
    "Scientists Develop Plastic-Eating Bacteria for Waste Management",
    "Virtual Reality Theme Park Opens, Featuring Zero Gravity",
    "New Blood Test Can Detect 50 Types of Cancer",
    "World's Longest Hiking Trail Completed, Spanning 14 Countries",
    "Floating City Project Begins Construction in the Pacific",
    "Gene Therapy Successfully Reverses Aging in Mice",
    "Global Agreement Reached on Universal Basic Income",
    "New Earbuds Offer Real-Time Language Translation",
    "Robot Chef Wins International Cooking Competition",
    "First Human-Animal Hybrid Embryos Created for Organ Transplants",
    "Holographic Teachers Introduced in Rural Schools",
    "World's First Underwater City Welcomes Residents",
    "New Treatment Uses Sound Waves to Destroy Cancer Cells",
    "Global Effort to Revive Extinct Species Shows Success",
    "AI System Solves Complex Climate Models, Improving Predictions",
    "Revolutionary Carbon Capture Technology Turns CO2 into Stone",
    "World's Smallest Pacemaker Implanted in Infant",
    "New Material Can Charge Batteries Using Ambient Humidity",
    "First Teleportation of Complex Quantum Data Achieved",
    "AI-Powered Drones Help Reforest Remote Areas",
    "Scientists Create Artificial Womb for Premature Babies",
    "New Recycling Process Turns Plastic into High-Quality Fuel",
    "Global Initiative to Map Ocean Floor Reaches Milestone",
    "Brain-Computer Interface Allows Paralyzed Patient to Walk",
    "World's Largest Vertical Farm Opens in Desert Region",
    "New App Uses AR to Teach Sign Language",
    "Breakthrough in Cold Fusion Energy Generation",
    "AI System Designs Revolutionary New Bicycle",
    "Scientists Develop Paint That Cools Buildings",
    "World's First Edible Water Bottle Hits Market",
    "New Solar Panel Design Doubles Energy Efficiency",
    "AI Creates New Periodic Table Element in Virtual Lab",
    "Historic Trade Agreement Unites African Continent",
    "Scientists Develop Fabric That Adapts to Body Temperature",
    "World's First Fully Recyclable Running Shoe Hits Market",
    "New Treatment Reverses Aging in Human Skin Cells",
    "AI Composer Creates Symphony Inspired by Whale Songs",
    "Global Coral Restoration Project Shows Promising Results",
    "New Technology Allows Crops to Grow in Saltwater",
    "World's First Brain-to-Brain Social Network Launches",
    "Scientists Achieve Room-Temperature Superconductivity",
    "New Technique Allows Paralyzed Person to Walk Again",
    "Global Reforestation Initiative Plants Billionth Tree",
    "AI System Predicts Earthquake With Unprecedented Accuracy",
    "World's Largest Butterfly Sanctuary Opens to Public",
    "New Technology Turns Nuclear Waste into Clean Energy",
    "Global Agreement Reached on Ethical AI Development",
    "Scientists Develop Self-Healing Concrete for Infrastructure",
    "Virtual Reality Used to Treat PTSD in Veterans",
    "New Species of 'Glass Frog' Discovered in Amazon",
    "World's Longest Suspension Bridge Opens to Traffic",
    "Breakthrough Allows Direct Brain-to-Text Communication",
    "Global Initiative to Clean Up Space Debris Launches",
    "New Vaccine Shows Promise Against Multiple Sclerosis",
    "World's First Floating Wind Farm Exceeds Energy Targets",
    "AI System Writes Bestselling Novel in 24 Hours",
    "Scientists Develop Pill to Extend Human Lifespan by Decades",
    "World's First Quantum Internet Network Established",
    "New Treatment Reverses Baldness in Clinical Trials",
    "Global Effort to Eradicate Polio Reaches Final Stages",
    "AI Predicts Protein Structures, Accelerating Drug Discovery",
    "World's Largest Carbon Capture Plant Goes Online",
    "New Sustainable Fabric Made from Coffee Grounds",
    "Global Treaty Bans All Single-Use Plastics",
    "Scientists Successfully Clone Extinct Species",
    "World's First Fully 3D-Printed House Completed",
    "New Plant-Based Meat Alternative Made from Seaweed",
    "Global Literacy Rates Reach All-Time High",
    "AI-Generated Virtual Influencer Gains Millions of Followers",
    "Scientists Develop Technique to Reverse Aging in Human Cells",
    "World's Largest Tidal Energy Project Begins Operations",
    "New Technology Enables Wireless Charging of Electric Vehicles While Driving",
    "Global Initiative Launched to Create Digital Twin of Earth",
    "AI System Discovers New Laws of Physics",
    "World's First Artificial Womb Facility Approved for Human Trials",
    "New Desalination Technology Solves Water Scarcity Issues",
    "Global Effort to Restore Earth's Ozone Layer Shows Significant Progress",
    "Local Bakery Wins National Pie Competition",
    "New Species of Deep Sea Creature Discovered",
    "Virtual Reality Orchestra Performs Sold-Out Concert",
    "Global Coffee Shortage Looms as Brazil Faces Drought",
    "Breakthrough in Quantum Computing Achieved",
    "Amateur Astronomer Spots Comet Missed by NASA",
    "Electric Aircraft Completes First Transatlantic Flight",
    "Ancient Roman Coin Hoard Found in Suburban Backyard",
    "Renewable Energy Now Cheaper Than Coal in All Major Markets",
    "World's Oldest Person Celebrates 120th Birthday",
    "AI-Generated Art Sells for Record Price at Auction",
    "New Study Links Gut Bacteria to Improved Mental Health",
    "Global Chess Tournament Ends in Surprise Upset",
    "Rare Blue Moon to Occur on New Year's Eve",
    "Scientists Develop Plastic-Eating Bacteria",
    "Local Woman Knits World's Longest Scarf",
    "New Plant-Based Meat Alternative Made from Seaweed",
    "Historic Peace Treaty Signed in Middle East",
    "Autonomous Taxis Launch in Major Cities Worldwide",
    "Lost Shakespeare Play Discovered in Attic",
    "Global Effort to Clean Oceans Shows Promising Results",
    "New Cancer Treatment Uses Patient's Own Cells",
    "World's Smallest Computer Fits on Grain of Rice",
    "International Space Station Grows First Fruits in Space",
    "Archaeological Dig Uncovers Ancient Board Game",
    "Record-Breaking Heat Wave Sweeps Across Europe",
    "New Language Discovered in Remote Mountain Village",
    "Virtual Fashion Show Features AI-Designed Clothing",
    "Global Literacy Rates Reach All-Time High",
    "Breakthrough in Fusion Energy Brings Clean Power Closer",
    "World's Largest Urban Rooftop Farm Opens",
    "New Technology Allows Paralyzed Individuals to Communicate",
    "Rare Triple Rainbow Phenomenon Captured on Camera",
    "Global Initiative Launches to Preserve Indigenous Languages",
    "Scientists Successfully Teleport Quantum Information",
    "World's First Fully 3D-Printed House Completed",
    "New Vaccine Shows Promise Against Multiple Sclerosis",
    "Hoverboard Racing Becomes Official Olympic Sport",
    "Artificial Leaf Converts CO2 to Clean Fuel",
    "World's Oldest Known Animal Cave Painting Discovered",
    "New Sustainable Fabric Made from Coffee Grounds",
    "Global Treaty Bans All Single-Use Plastics",
    "AI System Predicts Earthquake With Unprecedented Accuracy",
    "World's Largest Vertical Garden Cleans City Air",
    "New Treatment Reverses Baldness in Clinical Trials",
    "First Commercial Moon Base Breaks Ground",
    "Global Chess Champion Defeated by AI in Historic Match",
    "New Species of Giant Tortoise Discovered in Galapagos",
    "World's First Lab-Grown Steak Hits Restaurant Menus",
    "Virtual Reality Theme Park Opens, Featuring Zero Gravity",
    "Global Coral Restoration Project Shows Promising Results",
    "New Blood Test Can Detect 50 Types of Cancer",
    "World's Longest Hiking Trail Completed, Spanning 14 Countries",
    "AI Composer Creates Symphony Inspired by Birdsong",
    "Scientists Develop Self-Healing Concrete",
    "World's First Underwater City Welcomes Residents",
    "New Technique Allows Paralyzed Person to Walk Again",
    "Global Reforestation Initiative Plants Billionth Tree",
    "Holographic Teachers Introduced in Rural Schools",
    "World's Oldest Time Capsule Opened After 1000 Years",
    "New Earbuds Offer Real-Time Language Translation",
    "Global Effort to Revive Extinct Species Shows Success",
    "AI System Solves 100-Year-Old Mathematical Problem",
    "World's First Floating Wind Farm Exceeds Energy Targets",
    "New Treatment Uses Sound Waves to Destroy Cancer Cells",
    "Global Agreement Reached on Space Traffic Management",
    "World's Smallest Pacemaker Implanted in Infant",
    "AI-Powered Drones Help Reforest Remote Areas",
    "Ancient Mayan City Discovered Using Satellite Imagery",
    "New Recycling Process Turns Plastic into High-Quality Fuel",
    "World's First Fully Autonomous Farm Harvests Inaugural Crop",
    "Scientists Create Artificial Leaf That Produces Clean Gas",
    "Global Initiative to Map Ocean Floor Reaches Milestone",
    "New App Uses AR to Teach Sign Language",
    "World's Largest Carbon Capture Plant Goes Online",
    "AI System Designs Revolutionary New Bicycle",
    "Rare 'Unicorn' Meteor Shower Expected Tonight",
    "New Technique Allows Crops to Grow in Saltwater",
    "World's First Brain-to-Brain Social Network Launches",
    "Ancient Egyptian Queen's Tomb Opened for First Time",
    "New Material Can Charge Batteries Using Ambient Humidity",
    "Global Effort to Eradicate Polio Reaches Final Stages",
    "AI Predicts Protein Structures, Accelerating Drug Discovery",
    "World's Largest Butterfly Sanctuary Opens to Public",
    "New Technology Turns Nuclear Waste into Clean Energy",
    "Global Agreement Reached on Ethical AI Development",
    "Scientists Develop Paint That Cools Buildings",
    "World's First Edible Water Bottle Hits Market",
    "AI System Writes Bestselling Novel in 24 Hours",
    "New Species of 'Glass Frog' Discovered in Amazon",
    "World's Longest Suspension Bridge Opens to Traffic",
    "Breakthrough Allows Direct Brain-to-Text Communication",
    "Global Initiative to Clean Up Space Debris Launches",
    "New Solar Panel Design Doubles Energy Efficiency",
    "World's Oldest DNA Extracted from Million-Year-Old Mammoth",
    "AI Creates New Periodic Table Element in Virtual Lab",
    "Historic Trade Agreement Unites African Continent",
    "Scientists Develop Fabric That Adapts to Body Temperature",
    "World's First Fully Recyclable Running Shoe Hits Market",
    "New Treatment Reverses Aging in Human Skin Cells",
]